version: "3.3"
services:

  php-fpm:
    images: foreverphp/php-fpm:7.4-r1
    container_name: foreverphp-php-fpm
    working_dir: /project
    volumes:
      - .:/project
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    ports:
      - "9001:9000"
    links:
      - mariadb:database  

  mariadb:
    image: mariadb:10.5.5
    container_name: foreverphp-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306"

  nginx:
    image: nginx:alpine
    container_name: foreverphp-nginx
    working_dir: /project
    volumes:
      - .:/project
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9080:80"
    links:
      - foreverphp-php-fpm

